# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JwmAF4d9wME1v2fWq7gL4o3vzAPPFqa9
"""

# Q1(a)

rows = 3
columns = 5

print("Number of rows =", rows)
print("Number of columns =", columns)
print("Size of matrix A =", rows, "x", columns)
# Q1(b)

import numpy as np

A = np.array([
    [1, 2, 3, 4, 5],
    [2, 1, 0, 1, 3],
    [1, 0, 2, 1, 4]
])

x = np.array([1, 2, 3, 4, 5])

T_x = A @ x

print("Input vector:", x)
print("Output vector:", T_x)
print("Domain = R^5")
print("Codomain = R^3")
# Q1(c)

rows = 4
columns = 6

print("Matrix A size =", rows, "x", columns)
print("Domain = R^6")
print("Codomain = R^4")

# Q2(i)
# T(x, y) = (3x - 2y, x + 4y)

def T(x, y):
    return (3*x - 2*y, x + 4*y)

# Check using random values
x, y = 2, 3
a, b = 4, 1

print("T(x, y) =", T(x, y))
print("T(a, b) =", T(a, b))

# This transformation is linear
print("T is Linear")
# Q2(ii)
# T(x, y) = (3x - 2y + 1, x + 4y)

def T(x, y):
    return (3*x - 2*y + 1, x + 4*y)

print("T(0, 0) =", T(0, 0))

# Since T(0,0) != (0,0), it is not linear
print("T is NOT Linear")
# Q2(iii)
# T(x, y) = (x^2, y)

def T(x, y):
    return (x**2, y)

print("T(0, 0) =", T(0, 0))

# The x^2 term makes the transformation non-linear
print("T is NOT Linear")
# Q2(iv)
# T(x, y, z) = (2x - 4y + 3z + b, 6x + cxyz)

# For linearity:
# b = 0
# c = 0

b = 0
c = 0

def T(x, y, z):
    return (
        2*x - 4*y + 3*z + b,
        6*x + c*x*y*z
    )

print("b =", b)
print("c =", c)
print("T(0, 0, 0) =", T(0, 0, 0))
print("T is Linear")

# Q3

import numpy as np

A = np.array([
    [0, 1],
    [1, 0]
])

u = np.array([4, 1])
v = np.array([2, 3])

# T(u)
Tu = A @ u

# T(v)
Tv = A @ v

# u + v
u_plus_v = u + v

# T(u + v)
T_u_plus_v = A @ u_plus_v

# T(u) + T(v)
Tu_plus_Tv = Tu + Tv

print("T(u) =", Tu)
print("T(v) =", Tv)
print("u + v =", u_plus_v)
print("T(u + v) =", T_u_plus_v)
print("T(u) + T(v) =", Tu_plus_Tv)

# Verify additivity
print("Additivity verified:", np.array_equal(T_u_plus_v, Tu_plus_Tv))

# Q4

import numpy as np

# Given:
# T(e1) = [2, -1, 3]
# T(e2) = [-1, 4, 2]

# Standard matrix of T
A = np.array([
    [2, -1],
    [-1, 4],
    [3, 2]
])

# Find T([3, -2])
x = np.array([3, -2])

Tx = A @ x

print("Matrix A:")
print(A)

print("\nT([3, -2]) =", Tx)

# Verify using:
# T(3e1 - 2e2) = 3T(e1) - 2T(e2)

Te1 = np.array([2, -1, 3])
Te2 = np.array([-1, 4, 2])

verification = 3 * Te1 - 2 * Te2

print("3T(e1) - 2T(e2) =", verification)

print("\nVerification:", np.array_equal(Tx, verification))

# Q5

import numpy as np

# Unit square corners
points = np.array([
    [0, 0],
    [1, 0],
    [1, 1],
    [0, 1]
])

# 1. 90° counterclockwise rotation
R = np.array([
    [0, -1],
    [1,  0]
])

# 2. Horizontal shear: e1 -> e1, e2 -> e2 + 2e1
S = np.array([
    [1, 2],
    [0, 1]
])

# Apply transformations
rotated = points @ R.T
sheared = points @ S.T

print("Original corners:")
print(points)

print("\nAfter 90° CCW rotation:")
print(rotated)

print("\nAfter horizontal shear:")
print(sheared)

# Q6

import numpy as np

# 90° counterclockwise rotation
R = np.array([
    [0, -1],
    [1,  0]
])

# Projection onto x-axis
P = np.array([
    [1, 0],
    [0, 0]
])

# Given vector
x = np.array([1, 2])

# First rotate, then project: PR
PR = P @ R

# First project, then rotate: RP
RP = R @ P

print("PR =")
print(PR)

print("\nRP =")
print(RP)

print("\nFor x =", x)

print("PR(x) =", PR @ x)
print("RP(x) =", RP @ x)

# Compare
print("\nAre PR and RP equal?", np.array_equal(PR, RP))

# Q7

import numpy as np

# Define a linear transformation
A = np.array([
    [2, 1],
    [1, 3]
])

def T(v):
    return A @ v

# Two points
x = np.array([1, 2])
y = np.array([5, 4])

# Midpoint z = (x + y) / 2
z = (x + y) / 2

# Calculate T(z)
Tz = T(z)

# Calculate midpoint of T(x) and T(y)
Tx = T(x)
Ty = T(y)

midpoint = (Tx + Ty) / 2

print("x =", x)
print("y =", y)
print("z =", z)

print("\nT(x) =", Tx)
print("T(y) =", Ty)
print("T(z) =", Tz)

print("\nMidpoint of T(x) and T(y) =", midpoint)

# Verify midpoint property
print("\nMidpoint property verified:",
      np.array_equal(Tz, midpoint))


# Translation S(x) = x + p
p = np.array([2, 3])

def S(v):
    return v + p

Sx = S(x)
Sy = S(y)
Sz = S(z)

translation_midpoint = (Sx + Sy) / 2

print("\nTranslation:")
print("S(z) =", Sz)
print("Midpoint of S(x) and S(y) =", translation_midpoint)

print("\nMidpoint property under translation:",
      np.array_equal(Sz, translation_midpoint))

# Q8

import numpy as np

# Given matrix A
A = np.array([
    [1, 2, 0, 1],
    [0, 1, 3, 2],
    [0, 0, 1, 4]
])

# Rank of A
rank = np.linalg.matrix_rank(A)

print("Matrix A:")
print(A)

print("\nRank of A =", rank)

# Number of rows and columns
m, n = A.shape

print("Rows =", m)
print("Columns =", n)

# Check whether T is onto
if rank == m:
    print("T is ONTO")
else:
    print("T is NOT ONTO")

# Check whether T is one-to-one
if rank == n:
    print("T is ONE-TO-ONE")
else:
    print("T is NOT ONE-TO-ONE")

# Example Ax = b
b = np.array([1, 2, 3])

# Find a solution using least squares
x, residuals, rank, singular_values = np.linalg.lstsq(A, b, rcond=None)

print("\nFor b =", b)
print("A solution x is:")
print(x)

print("\nCheck Ax:")
print(A @ x)

# Q9

import numpy as np

# (a) R^2 -> R^3
A = np.array([
    [1, 0],
    [0, 1],
    [0, 0]
])

rank = np.linalg.matrix_rank(A)

print("(a) R^2 -> R^3")
print("Rank =", rank)

if rank == 3:
    print("Onto: YES")
else:
    print("Onto: NO")


# (b) R^3 -> R^2
A = np.array([
    [1, 0, 0],
    [0, 1, 0]
])

rank = np.linalg.matrix_rank(A)

print("\n(b) R^3 -> R^2")
print("Rank =", rank)

if rank == 3:
    print("One-to-one: YES")
else:
    print("One-to-one: NO")


# (c) R^2 -> R^3
A = np.array([
    [1, 0],
    [0, 1],
    [0, 0]
])

rank = np.linalg.matrix_rank(A)

print("\n(c) R^2 -> R^3")
print("Rank =", rank)

if rank == 2:
    print("One-to-one: YES")
else:
    print("One-to-one: NO")


# (d) R^3 -> R^2
A = np.array([
    [1, 0, 0],
    [0, 1, 0]
])

rank = np.linalg.matrix_rank(A)

print("\n(d) R^3 -> R^2")
print("Rank =", rank)

if rank == 2:
    print("Onto: YES")
else:
    print("Onto: NO")

# Q10

import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# Upload your image and change the file name here
image_path = "your_image.jpg"

# Read image
img = Image.open(image_path).convert("RGB")
img_array = np.array(img)

# Image dimensions
height, width, _ = img_array.shape

# Centre of the image
cx = width / 2
cy = height / 2

# Create pixel coordinates relative to image centre
y, x = np.mgrid[0:height, 0:width]

x_centered = x - cx
y_centered = cy - y

points = np.vstack((x_centered.ravel(), y_centered.ravel()))

# Transformation matrices
A1 = np.array([
    [2, 0],
    [0, 0.5]
])

A2 = np.array([
    [0, -1],
    [1,  0]
])

A3 = np.array([
    [1, 1],
    [0, 1]
])

A4 = np.array([
    [-1, 0],
    [0, 1]
])

A5 = np.array([
    [1, 0],
    [0, 0]
])

matrices = {
    "A1 - Resize": A1,
    "A2 - 90 Degree Rotation": A2,
    "A3 - Shear": A3,
    "A4 - Flip": A4,
    "A5 - Projection": A5
}


def transform_image(A):
    # Transform coordinates
    new_points = A @ points

    new_x = np.round(new_points[0] + cx).astype(int)
    new_y = np.round(cy - new_points[1]).astype(int)

    # Create blank image
    result = np.zeros_like(img_array)

    # Keep coordinates inside image
    valid = (
        (new_x >= 0) & (new_x < width) &
        (new_y >= 0) & (new_y < height)
    )

    old_x = x.ravel()[valid]
    old_y = y.ravel()[valid]

    result[new_y[valid], new_x[valid]] = img_array[old_y, old_x]

    return result


# Print T(e1), T(e2), rank and information loss
e1 = np.array([1, 0])
e2 = np.array([0, 1])

for name, A in matrices.items():

    print("\n", name)
    print("Matrix:")
    print(A)

    print("T(e1) =", A @ e1)
    print("T(e2) =", A @ e2)

    rank = np.linalg.matrix_rank(A)
    print("Rank =", rank)

    if rank < 2:
        print("Information loss: YES")
    else:
        print("Information loss: NO")

    transformed = transform_image(A)

    plt.figure(figsize=(5, 5))
    plt.imshow(transformed)
    plt.title(name)
    plt.axis("off")
    plt.show()

# Q11 - Image Transformation Toolbox

import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# Upload image
image_path = input("Enter image file path (.jpg/.png): ")

img = Image.open(image_path).convert("RGB")
img_array = np.array(img)

def show_image(image, title):
    plt.figure(figsize=(6, 6))
    plt.imshow(image)
    plt.title(title)
    plt.axis("off")
    plt.show()

def rotate_image(image, angle):
    return image.rotate(angle, expand=True)

def resize_image(image, scale):
    w, h = image.size
    return image.resize((int(w * scale), int(h * scale)))

def flip_image(image, direction):
    if direction == "horizontal":
        return image.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
    elif direction == "vertical":
        return image.transpose(Image.Transpose.FLIP_TOP_BOTTOM)

def shear_image(image, shear):
    w, h = image.size
    matrix = (1, shear, 0, 0, 1, 0)
    return image.transform(
        (w, h),
        Image.Transform.AFFINE,
        matrix
    )

def custom_matrix(image, A):
    img_array = np.array(image)
    h, w, _ = img_array.shape

    cx = w / 2
    cy = h / 2

    y, x = np.mgrid[0:h, 0:w]

    x_centered = x - cx
    y_centered = cy - y

    points = np.vstack((
        x_centered.ravel(),
        y_centered.ravel()
    ))

    new_points = A @ points

    new_x = np.round(new_points[0] + cx).astype(int)
    new_y = np.round(cy - new_points[1]).astype(int)

    result = np.zeros_like(img_array)

    valid = (
        (new_x >= 0) & (new_x < w) &
        (new_y >= 0) & (new_y < h)
    )

    old_x = x.ravel()[valid]
    old_y = y.ravel()[valid]

    result[
        new_y[valid],
        new_x[valid]
    ] = img_array[old_y, old_x]

    return Image.fromarray(result)


# Menu
while True:

    print("\n----- Image Transformation Toolbox -----")
    print("1. Rotate")
    print("2. Resize")
    print("3. Flip")
    print("4. Shear")
    print("5. Custom Matrix")
    print("6. Reset")
    print("7. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        angle = float(input("Enter rotation angle: "))
        img = rotate_image(img, angle)
        show_image(img, "Rotated Image")

    elif choice == "2":
        scale = float(input("Enter resize scale: "))
        img = resize_image(img, scale)
        show_image(img, "Resized Image")

    elif choice == "3":
        direction = input(
            "Enter direction (horizontal/vertical): "
        ).lower()

        img = flip_image(img, direction)
        show_image(img, "Flipped Image")

    elif choice == "4":
        shear = float(input("Enter shear value: "))

        img = shear_image(img, shear)
        show_image(img, "Sheared Image")

    elif choice == "5":
        print("\nEnter 2x2 transformation matrix:")

        a = float(input("a11 = "))
        b = float(input("a12 = "))
        c = float(input("a21 = "))
        d = float(input("a22 = "))

        A = np.array([
            [a, b],
            [c, d]
        ])

        img = custom_matrix(img, A)
        show_image(img, "Custom Matrix Transformation")

    elif choice == "6":
        img = Image.open(image_path).convert("RGB")
        print("Image reset successfully.")
        show_image(img, "Original Image")

    elif choice == "7":
        print("Exiting Image Transformation Toolbox.")
        break

    else:
        print("Invalid choice. Please try again.")
